# Configure Travis CI
# https://travis-ci.org/

matrix:
  include:
    - language: go
      go:
        - master
      script:
        - cd src && go install

#    - language: javascript

notifications:
  email:
    on_success: never
    on_failure: never
