# Configure Travis CI
# https://travis-ci.org/

matrix:
  include:
    - language: go
      go:
        - master
      before_script:
        - cd src
      script:
        - go install # Compile the Go code
        - golangci-lint run # Run the Golang linter

    - language: node_js
      node_js:
        - node
      before_script:
        - cd public/js
        - npm install
      script:
        - cd
        - ./build_client.sh

notifications:
  email:
    on_success: never
    on_failure: never
