# Configure Travis CI
# https://travis-ci.org/

matrix:
  include:
    - language: go
      go:
        - master
      before_script:
        - cd src
      script:
        # Compile the Go code
        - go install
        # Install the Go linter
        # (v1.13.1 is the latest as of Jan 2019)
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.13.1
        # Run the Golang linter
        - golangci-lint run

    - language: node_js
      node_js:
        - node
      before_script:
        - cd public/js
        - npm install
      script:
        - cd ../..
        - ./build_client.sh

notifications:
  email:
    on_success: never
    on_failure: never
