name: Spell checking
on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Spell checker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: check-spelling/check-spelling@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
