name: Spell checking
on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Spell checker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 2
    - uses: ./
      with:
        bucket: .github/actions
        project: spelling
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
